#!/bin/bash

# Get all of the third-party repos and put them where we want them.
git clone git@github.com:enjrolas/beta-cube-library.git
mkdir spark-firmware
git clone https://github.com/spark/firmware.git spark-firmware/firmware
git clone https://github.com/spark/core-common-lib.git spark-firmware/core-common-lib
git clone https://github.com/spark/core-communication-lib.git spark-firmware/core-communication-lib

# Modify the FIRMWARE_DIR in beta-cube-library to point to right place
sed -i .bak -e "s@^FIRMWARE_DIR =.*@FIRMWARE_DIR = `pwd`/spark-firmware/firmware/@" \
  beta-cube-library/makefile 


